server:
  port: 8080

spring:
  application:
    name: config-client-1
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: false
    bus:
      id: ${spring.application.name}
      enabled: true
      destination: my-config-bus
      ack:
        mode: none
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info,busenv
  endpoint:
    health:
      show-details: always
