server:
  port: 8080

spring:
  application:
    name: config-client-1
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
    bus:
      enabled: true
      destination: config-client-1
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,refresh,info,busenv
  endpoint:
    health:
      show-details: always
